### ISSUE TITLE
de.viadee.bpm.vPAV.config.reader.XmlRule cannot be cast to de.viadee.bpm.vPAV.config.reader.XmlRuleSet

### ISSUE THREAD

**Issue by fkoehne** [viadee/vPAV#114]
**Describe the bug**
@Test
  public void validateModel() {
     Assert.assertTrue("Model inconsistency found. Please check target folder for validation output",
             ProcessApplicationValidator.findModelInconsistencies().isEmpty());
  }

-------------------------------------------------------------------------------
Test set: ....ModelValidationTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.266 sec <<< FAILURE!
validateModel(.....ModelValidationTest)  Time elapsed: 0.191 sec  <<< ERROR!
java.lang.ClassCastException: de.viadee.bpm.vPAV.config.reader.XmlRule cannot be cast to de.viadee.bpm.vPAV.config.reader.XmlRuleSet
                at de.viadee.bpm.vPAV.config.reader.XmlConfigReader.read(XmlConfigReader.java:70)
                at de.viadee.bpm.vPAV.Runner.readConfig(Runner.java:138)
                at de.viadee.bpm.vPAV.Runner.viadeeProcessApplicationValidator(Runner.java:95)
                at de.viadee.bpm.vPAV.ProcessApplicationValidator.createRunner(ProcessApplicationValidator.java:188)
                at de.viadee.bpm.vPAV.ProcessApplicationValidator.findModelErrors(ProcessApplicationValidator.java:108)
                at de.betterorange.boqa2ee.ModelValidationTest.validateModel(ModelValidationTest.java:20)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
                at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
                at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
                at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Maven version
 - Java version
 - Version [e.g. 2.7.0]

**Additional context**

**Comment by fkoehne** [comment]
... Versions and ruleset are to be clarified.

**Comment by fkoehne** [comment]
`<dependency>
      <groupId>de.viadee</groupId>
      <artifactId>viadeeProcessApplicationValidator</artifactId>
      <version>2.8.1</version>
      <scope>test</scope>
    </dependency>

Und hier das Ruleset.xml:

<rule>
  <name>HasParentRuleSet</name>
  <state>true</state>
</rule>
`

**Comment by fkoehne** [comment]
<dependency>
      <groupId>de.viadee</groupId>
      <artifactId>viadeeProcessApplicationValidator</artifactId>
      <version>2.8.1</version>
      <scope>test</scope>
    </dependency>

Und hier das Ruleset.xml:

<rule>
  <name>HasParentRuleSet</name>
  <state>true</state>
</rule>

**Comment by fkoehne** [comment]
><dependency>
>      <groupId>de.viadee</groupId>
>     <artifactId>viadeeProcessApplicationValidator</artifactId>
>      <version>2.8.1</version>
>     <scope>test</scope>
>    </dependency>
>
>Und hier das Ruleset.xml:
>
><rule>
>  <name>HasParentRuleSet</name>
>  <state>true</state>
></rule>

**Comment by fkoehne** [comment]
... enclosing ruleSet-Tag was missing.

**Comment by sdibernardo** [comment]
Issue has been resolved :)
