### ISSUE TITLE
Basedir for kotlin project

### ISSUE THREAD

**Issue by KotskinKotskin** [viadee/vPAV#131]
**Describe the bug**
When i try to run specific test ModelConsistenctTest inside Kotlin project i get:

java.lang.IllegalStateException: basedir src\main\java does not exist.

	at org.apache.tools.ant.DirectoryScanner.scan(DirectoryScanner.java:886)
	at de.viadee.bpm.vPAV.FileScanner.<init>(FileScanner.java:102)
	at de.viadee.bpm.vPAV.Runner.viadeeProcessApplicationValidator(Runner.java:98)
	at de.viadee.bpm.vPAV.ProcessApplicationValidator.createRunner(ProcessApplicationValidator.java:192)
	at de.viadee.bpm.vPAV.ProcessApplicationValidator.findModelErrors(ProcessApplicationValidator.java:82)
	at ru.tinkoff.bpm.smepushingservice.process.ModelConsistencyTest.validateModel(ModelConsistenctyTest.kt:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

**Additional context**
i use graddle and kotlin. 

Can you made basedir as properties?

**Comment by sdibernardo** [comment]
Can you provide a minimal working example and host it on git? We´d like to dig into that issue a little bit deeper. Also, feel free to create a PR.

Best regards

**Comment by KotskinKotskin** [comment]
https://github.com/KotskinKotskin/vpav-camunda-kotlin-issue
Run ModelConsistencyTest 

I look into the source and think they're more work, then just add properties, because your library looking for .java files.

**Comment by sdibernardo** [comment]
This should be fixed with #134, but to ensure vPAV runs properly, I need a running example that consists of a model + additional delegate. 
You can add now the following to properties to the vpav.properties file: 
`scanpath=src/main/kotlin` and 
`filepattern=**/*.k`. 

The latest snapshot version already includes those changes.
Best regards

**Comment by KotskinKotskin** [comment]
hi, thanks! I will add an example tomorrow

**Comment by sdibernardo** [comment]
@KotskinKotskin Any feedback regarding vPAV under Kotlin?

**Comment by KotskinKotskin** [comment]
Hi, sorry, foget about that. I will try check on this week.

**Comment by sdibernardo** [comment]
Can this issue be closed?
