### ISSUE TITLE
Exception thrown during usage of case study

### ISSUE THREAD

**Issue by sdibernardo** [viadee/vPAV#156]
Full stacktrace here. Sourcecode will be provided internally.
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at de.viadee.bpm.vPAV.processing.VariablesExtractor.processInvokeStmt(VariablesExtractor.java:437)
	at de.viadee.bpm.vPAV.processing.VariablesExtractor.blockIterator(VariablesExtractor.java:245)
	at de.viadee.bpm.vPAV.processing.JavaReaderStatic.graphIterator(JavaReaderStatic.java:363)
	at de.viadee.bpm.vPAV.processing.JavaReaderStatic.classFetcherRecursive(JavaReaderStatic.java:296)
	at de.viadee.bpm.vPAV.processing.JavaReaderStatic.classFetcher(JavaReaderStatic.java:184)
	at de.viadee.bpm.vPAV.processing.JavaReaderStatic.getVariablesFromJavaDelegate(JavaReaderStatic.java:114)
	at de.viadee.bpm.vPAV.processing.ProcessVariableReader.findVariablesInExpression(ProcessVariableReader.java:1126)
	at de.viadee.bpm.vPAV.processing.ProcessVariableReader.getVariablesFromTask(ProcessVariableReader.java:749)
	at de.viadee.bpm.vPAV.processing.ProcessVariableReader.getVariablesFromElement(ProcessVariableReader.java:126)
	at de.viadee.bpm.vPAV.processing.ElementGraphBuilder.createVariablesOfFlowElement(ElementGraphBuilder.java:274)
	at de.viadee.bpm.vPAV.processing.ElementGraphBuilder.createProcessGraph(ElementGraphBuilder.java:185)
	at de.viadee.bpm.vPAV.processing.BpmnModelDispatcher.dispatchWithVariables(BpmnModelDispatcher.java:101)
	at de.viadee.bpm.vPAV.Runner.checkModel(Runner.java:584)
	at de.viadee.bpm.vPAV.Runner.checkModels(Runner.java:546)
	at de.viadee.bpm.vPAV.Runner.createIssues(Runner.java:252)
	at de.viadee.bpm.vPAV.Runner.viadeeProcessApplicationValidator(Runner.java:106)
	at de.viadee.bpm.vPAV.ProcessApplicationValidator.createRunner(ProcessApplicationValidator.java:183)
	at de.viadee.bpm.vPAV.ProcessApplicationValidator.findModelInconsistencies(ProcessApplicationValidator.java:63)
	at de.viadee.bpm.vPAV.ProcessApplicationValidator.findModelErrors(ProcessApplicationValidator.java:75)
	at de.viasurance.kglasbruch.test.ProcessValidationTest.validateModel(ProcessValidationTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by sdibernardo** [comment]
Should be hotfixed with [990c597bf82cb2b86048e336d8f443c7804f4eea](url)

**Comment by TamaraGunkel** [comment]
The hotfix temporarily fixes that problem. However, the problem is that variables are insufficiently backtracked. I opened a new issue for that (see #157).
